
/* Data loading Time dimension table */

INSERT INTO TIME_DIM (HOUR,
						MINS,
						DAY,
						WEEKDAY,
						WEEKDAY_NAME,
						MONTHNAME,
						MONTH_NO,
						QUARTER,
						YEAR)

SELECT 	YEAR,
		MONTH_NO,
		CASE MONTHNAME
		WHEN 1 THEN 'JANUARY'
		WHEN 2 THEN 'FEBRUARY'
		WHEN 3 THEN 'MARCH'
		WHEN 4 THEN 'APRIL'
		WHEN 5 THEN 'MAY'
		WHEN 6 THEN 'JUNE'
		WHEN 7 THEN 'JULY'
		WHEN 8 THEN 'AUGUST'
		WHEN 9 THEN 'SEPTEMBER'
		WHEN 10 THEN 'OCTOBER'
		WHEN 11 THEN 'NOVEMBER'
		WHEN 11 THEN 'DECEMBER'
		END AS MONTH_NAME
FROM
(	

SELECT YEAR,MONTH_NO,MONTHNAME FROM ABERPORTH_LZ
UNION
SELECT YEAR,MONTH_NO,MONTHNAME FROM ARMAGH_LZ
UNION 
SELECT YEAR,MONTH_NO,MONTHNAME FROM BALLYPATRICKDATA_LZ
UNION 
SELECT YEAR,MONTH_NO,MONTHNAME FROM BRADFORDDATA_LZ
UNION 
SELECT YEAR,MONTH_NO,MONTHNAME FROM BRAEMAR_LZ
)

/* Data loading Station dimension table */
INSERT INTO STATION_DIM (
						LATITUDE,
						LONGITUDE,
						CITY,
						CITYZIP,
						LOCATION
						)

SELECT LATITUDE,LATITUDE,CITY,CITYZIP,LOCATION 
FROM ABERPORTH_LZ
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = ABERPORTH_LZ.YEAR
AND TIME_DIM.MONTH_NO = ABERPORTH_LZ.MONTH

UNION

SELECT LATITUDE,LATITUDE,CITY,CITYZIP,LOCATION  
FROM ARMAGH_LZ
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = ARMAGH_LZ.YEAR
AND TIME_DIM.MONTH_NO = ARMAGH_LZ.MONTH

UNION 

SELECT LATITUDE,LATITUDE,CITY,CITYZIP,LOCATION 
FROM BALLYPATRICKDATA_LZ
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = BALLYPATRICKDATA_LZ.YEAR
AND TIME_DIM.MONTH_NO = BALLYPATRICKDATA_LZ.MONTH

UNION 

SELECT LATITUDE,LATITUDE,CITY,CITYZIP,LOCATION 
FROM BRADFORDDATA_LZ
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = BRADFORDDATA_LZ.YEAR
AND TIME_DIM.MONTH_NO = BRADFORDDATA_LZ.MONTH

UNION 

SELECT LATITUDE,LATITUDE,CITY,CITYZIP,LOCATION 
FROM BRAEMAR_LZ
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = BRAEMAR_LZ.YEAR
AND TIME_DIM.MONTH_NO = BRAEMAR_LZ.MONTH


/* Data loading Station dimension table */

INSERT INTO SUNSHINE_DATA_DIM (
						ABERPORTH_LZ.CITYZIP,
						ESTIMATED_DATA_IND,
						PROVISIONAL_IND
						)

SELECT LATITUDE,LATITUDE,CITY,CITYZIP,LOCATION 
FROM ABERPORTH_LZ
INNER JOIN STATION_DIM
ON STATION_DIM.CITYZIP = ABERPORTH_LZ.CITYZIP
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = ABERPORTH_LZ.YEAR
AND TIME_DIM.MONTH_NO = ABERPORTH_LZ.MONTH

UNION

SELECT LATITUDE,LATITUDE,CITY,ARMAGH_LZ.CITYZIP,LOCATION  
FROM ARMAGH_LZ
INNER JOIN STATION_DIM
ON STATION_DIM.CITYZIP = ARMAGH_LZ.CITYZIP
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = ARMAGH_LZ.YEAR
AND TIME_DIM.MONTH_NO = ARMAGH_LZ.MONTH

UNION 

SELECT LATITUDE,LATITUDE,CITY,BALLYPATRICKDATA_LZ.CITYZIP,LOCATION 
FROM BALLYPATRICKDATA_LZ
INNER JOIN STATION_DIM
ON STATION_DIM.CITYZIP = BALLYPATRICKDATA_LZ.CITYZIP
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = BALLYPATRICKDATA_LZ.YEAR
AND TIME_DIM.MONTH_NO = BALLYPATRICKDATA_LZ.MONTH

UNION 

SELECT LATITUDE,LATITUDE,CITY,BRADFORDDATA_LZ.CITYZIP,LOCATION 
FROM BRADFORDDATA_LZ
INNER JOIN STATION_DIM
ON STATION_DIM.CITYZIP = BRADFORDDATA_LZ.CITYZIP
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = BRADFORDDATA_LZ.YEAR
AND TIME_DIM.MONTH_NO = BRADFORDDATA_LZ.MONTH

UNION 

SELECT LATITUDE,LATITUDE,CITY,BRAEMAR_LZ.CITYZIP,LOCATION 
FROM BRAEMAR_LZ
INNER JOIN STATION_DIM
ON STATION_DIM.CITYZIP = BRAEMAR_LZ.CITYZIP
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = BRAEMAR_LZ.YEAR
AND TIME_DIM.MONTH_NO = BRAEMAR_LZ.MONTH


/* Data loading Waether fact table */

INSERT INTO WEATHER_FACT (
						TIME_ID,
						STATION_ID,
						MIN_TEMP,
						MAX_TEMP,
						RAINFALL_MM,
						AFFECT_DAYS,
						SUN_HOURS
						)

SELECT TIME_DIM.TIME_ID,STATION_DIM.STATION_ID,MIN_TEMP,MAX_TEMP,RAINFALL_MM,AFFECT_DAYS,SUN_HOURS
FROM ABERPORTH_LZ
INNER JOIN STATION_DIM
ON STATION_DIM.CITYZIP = ABERPORTH_LZ.CITYZIP
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = ABERPORTH_LZ.YEAR
AND TIME_DIM.MONTH_NO = ABERPORTH_LZ.MONTH

UNION

SELECT TIME_DIM.TIME_ID,STATION_DIM.STATION_ID,MIN_TEMP,MAX_TEMP,RAINFALL_MM,AFFECT_DAYS,SUN_HOURS  
FROM ARMAGH_LZ
INNER JOIN STATION_DIM
ON STATION_DIM.CITYZIP = ARMAGH_LZ.CITYZIP
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = ARMAGH_LZ.YEAR
AND TIME_DIM.MONTH_NO = ARMAGH_LZ.MONTH

UNION 

SELECT TIME_DIM.TIME_ID,STATION_DIM.STATION_ID,MIN_TEMP,MAX_TEMP,RAINFALL_MM,AFFECT_DAYS,SUN_HOURS 
FROM BALLYPATRICKDATA_LZ
INNER JOIN STATION_DIM
ON STATION_DIM.CITYZIP = BALLYPATRICKDATA_LZ.CITYZIP
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = BALLYPATRICKDATA_LZ.YEAR
AND TIME_DIM.MONTH_NO = BALLYPATRICKDATA_LZ.MONTH

UNION 

SELECT TIME_DIM.TIME_ID,STATION_DIM.STATION_ID,MIN_TEMP,MAX_TEMP,RAINFALL_MM,AFFECT_DAYS,SUN_HOURS
FROM BRADFORDDATA_LZ
INNER JOIN STATION_DIM
ON STATION_DIM.CITYZIP = BRADFORDDATA_LZ.CITYZIP
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = BRADFORDDATA_LZ.YEAR
AND TIME_DIM.MONTH_NO = BRADFORDDATA_LZ.MONTH

UNION 

SELECT TIME_DIM.TIME_ID,STATION_DIM.STATION_ID,MIN_TEMP,MAX_TEMP,RAINFALL_MM,AFFECT_DAYS,SUN_HOURS
FROM BRAEMAR_LZ
INNER JOIN STATION_DIM
ON STATION_DIM.CITYZIP = BRAEMAR_LZ.CITYZIP
INNER JOIN TIME_DIM 
ON TIME_DIM.YEAR = BRAEMAR_LZ.YEAR
AND TIME_DIM.MONTH_NO = BRAEMAR_LZ.MONTH