/* THE TIME_DIM TABLE CONTAIN THE DIMENSIONAL INFORMATION OF THE DATE AND TIME */

CREATE TABLE TIME_DIM
(
    TIME_ID INT PRIMARY KEY IDENTITY (1, 1),
	DATE_VAL DATETIME,
	START_DATE DATETIME,
	END_DATE DATETIME,
	HOUR INT,
	MINS INT,
	DAY INT,
	WEEKDAY INT,
	WEEKDAY_NAME VARCHAR(10),
	MONTHNAME VARCHAR(15),
	MONTH_NO INT,
	QUARTER INT,
	YEAR INT
)

/* THE STATION_DIM TABLE CONTAIN THE DIMENSIONAL INFORMATION OF THE ALLSTATIONS */

CREATE TABLE STATION_DIM
(
STATION_ID INT PRIMARY KEY IDENTITY (1, 1),
LATITUDE DECIMAL(10,3),
LONGITUDE DECIMAL(10,3),
STATION_CITY VARCHAR(50),
CITYZIP INT,
LOCATION VARCHAR(50)
)

---------------------------------------------------------------------------------------------------------
/* THE SUNSHINE_DATA_DIM TABLE CONTAIN THE DIMENSIONAL INFORMATION SUNSHINE DATA SOURCE */

CREATE TABLE SUNSHINE_DATA_DIM
(
    SUNSHINE_ID INT PRIMARY KEY IDENTITY (1, 1),
	CITYZIP INT,
	SUNSHINE_DATA_SOURCE VARCHAR(50)
)
-----------------------------------------------------------------------------------------------------

/* THE IND_DIM TABLE CONTAIN THE JUNK DIMENSION REALETED TO THE  THE WAETHER DATA */

CREATE TABLE IND_DIM
(
    IND_ID INT PRIMARY KEY IDENTITY (1, 1),
	CITYZIP INT,
	ESTIMATED_DATA_IND CHAR(1),
	PROVISIONAL_IND CHAR(1)
)

--------------------------------------------------------------------------------------------------------------------

/* THE WEATHER_FACT TABLE CONTAIN THE FACT INFORMATION OF THE WAETHER DATA */

CREATE TABLE WEATHER_FACT
(
    
	TIME_ID NUMBER,
	STATION_ID NUMBER,
	MIN_TEMP DECIMAL(5,2),
	MAX_TEMP DECIMAL(5,2),
	RAINFALL_MM DECIMAL(5,2),
	AFFECT_DAYS DECIMAL(5,2),
	SUN_HOURS DECIMAL(5,2)
	
)

