
/* CSV DATA POPULATING INTO BRAEMAR_LZ TABLE */
BULK INSERT BRAEMAR_LZ
    FROM 'C:\CSVDATA\BRAEMAR.CSV'
    WITH
    (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',  
    ROWTERMINATOR = '\N',   
    ERRORFILE = 'C:\CSVDATA\BRAEMARERRORROWS.CSV',
    TABLOCK
    )


/* CSV DATA POPULATING INTO BRADFORDDATA_LZ TABLE */

BULK INSERT BRADFORDDATA_LZ
    FROM 'C:\CSVDATA\BRADFORDDATA.CSV'
    WITH
    (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',  
    ROWTERMINATOR = '\N',   
    ERRORFILE = 'C:\CSVDATA\BRADFORDDATAERRORROWS.CSV',
    TABLOCK
    )
	
/* CSV DATA POPULATING INTO BALLYPATRICKDATA_LZ TABLE */
BULK INSERT BALLYPATRICKDATA_LZ
    FROM 'C:\CSVDATA\BALLYPATRICKDATA.CSV'
    WITH
    (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',  
    ROWTERMINATOR = '\N',   
    ERRORFILE = 'C:\CSVDATA\BALLYPATRICKDATAERRORROWS.CSV',
    TABLOCK
    )	
	
/* CSV DATA POPULATING INTO ARMAGH_LZ TABLE */
BULK INSERT ARMAGH_LZ
    FROM 'C:\CSVDATA\ARMAGH.CSV'
    WITH
    (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',  
    ROWTERMINATOR = '\N',   
    ERRORFILE = 'C:\CSVDATA\ARMAGHERRORROWS.CSV',
    TABLOCK
    )
	
/* CSV DATA POPULATING INTO ABERPORTH_LZ TABLE */
BULK INSERT ABERPORTH_LZ
    FROM 'C:\CSVDATA\ABERPORTH.CSV'
    WITH
    (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',  
    ROWTERMINATOR = '\N',   
    ERRORFILE = 'C:\CSVDATA\ABERPORTHERRORROWS.CSV',
    TABLOCK
    )