
/*LANDING ZONE TABLE [ABERPORTH_LZ] FOR ABERPORTH
WHICH POPULATED DATA FORM "ABERPORTH.CSV" FORM
WEATHER_EXTERNAL DIRECTORY
*/


CREATE TABLE ABERPORTH_LZ
(
    YEAR INT,
	MONTH INT,
	MIN_TEMP DECIMAL(5,2),
	MAX_TEMP DECIMAL(5,2),
	AFFECT_DAYS INT,
	RAINFALL_MM	DECIMAL(5,2),
	SUN_HOURS DECIMAL(5,2),
	ESTIMATED_DATA_IND CHAR(1),
	SUNSHINEDATA_SOURCE	VARCHAR(50),
	PROVISIONAL_IND	CHAR(1),
	CITY VARCHAR(50),
	CITYZIP INT,
	LOCATION VARCHAR(50),	
	LATITUDE DECIMAL(10,3),	
	LONGITUDE DECIMAL(10,3)
)

-------------------------------------------------------------------------------------------------

/*LANDING ZONE TABLE [ARMAGH_LZ] FOR ARMAGH
WHICH POPULATED DATA FORM "ARMAGH.CSV" FORM
WEATHER_EXTERNAL DIRECTORY
*/


CREATE TABLE ARMAGH_LZ
(
    YEAR INT,
	MONTH INT,
	MIN_TEMP DECIMAL(5,2),
	MAX_TEMP DECIMAL(5,2),
	AFFECT_DAYS INT,
	RAINFALL_MM	DECIMAL(5,2),
	SUN_HOURS DECIMAL(5,2),
	ESTIMATED_DATA_IND CHAR(1),
	SUNSHINEDATA_SOURCE	VARCHAR(50),
	PROVISIONAL_IND	CHAR(1),
	CITY VARCHAR(50),
	CITYZIP INT,
	LOCATION VARCHAR(50),	
	LATITUDE DECIMAL(10,3),	
	LONGITUDE DECIMAL(10,3)
)



------------------------------------------------------------------------------
/*LANDING ZONE TABLE  [BALLYPATRICKDATA_LZ]FOR BALLYPATRICKDATA
 WHICH POPULATED DATA FORM "BALLYPATRICKDATA.CSV" FORM
WEATHER_EXTERNAL DIRECTORY
*/

CREATE TABLE BALLYPATRICKDATA_LZ
(
    YEAR INT,
	MONTH INT,
	MIN_TEMP DECIMAL(5,2),
	MAX_TEMP DECIMAL(5,2),
	AFFECT_DAYS INT,
	RAINFALL_MM	DECIMAL(5,2),
	SUN_HOURS DECIMAL(5,2),
	ESTIMATED_DATA_IND CHAR(1),
	SUNSHINEDATA_SOURCE	VARCHAR(50),
	PROVISIONAL_IND	CHAR(1),
	CITY VARCHAR(50),
	CITYZIP INT,
	LOCATION VARCHAR(50),	
	LATITUDE DECIMAL(10,3),	
	LONGITUDE DECIMAL(10,3)
)


----------------------------------------------------------------------------

/*LANDING ZONE TABLE  [BRADFORDDATA_LZ] FOR BRADFORDDATA
WHICH POPULATED DATA FORM "BRADFORDDATA.CSV" FORM
WEATHER_EXTERNAL DIRECTORY
*/

CREATE TABLE BRADFORDDATA_LZ
(
    YEAR INT,
	MONTH INT,
	MIN_TEMP DECIMAL(5,2),
	MAX_TEMP DECIMAL(5,2),
	AFFECT_DAYS INT,
	RAINFALL_MM	DECIMAL(5,2),
	SUN_HOURS DECIMAL(5,2),
	ESTIMATED_DATA_IND CHAR(1),
	SUNSHINEDATA_SOURCE	VARCHAR(50),
	PROVISIONAL_IND	CHAR(1),
	CITY VARCHAR(50),
	CITYZIP INT,
	LOCATION VARCHAR(50),	
	LATITUDE DECIMAL(10,3),	
	LONGITUDE DECIMAL(10,3)
)



----------------------------------------------------------------------------------
/*LANDING ZONE TABLE [BRAEMAR_LZ] FOR BRAEMAR
 WHICH POPULATED DATA FORM "BRAEMAR.CSV" FORM
WEATHER_EXTERNAL DIRECTORY
*/

CREATE TABLE BRAEMAR_LZ
(
    YEAR INT,
	MONTH INT,
	MIN_TEMP DECIMAL(5,2),
	MAX_TEMP DECIMAL(5,2),
	AFFECT_DAYS INT,
	RAINFALL_MM	DECIMAL(5,2),
	SUN_HOURS DECIMAL(5,2),
	ESTIMATED_DATA_IND CHAR(1),
	SUNSHINEDATA_SOURCE	VARCHAR(50),
	PROVISIONAL_IND	CHAR(1),
	CITY VARCHAR(50),
	CITYZIP INT,
	LOCATION VARCHAR(50),	
	LATITUDE DECIMAL(10,3),	
	LONGITUDE DECIMAL(10,3)
)

