
/* The following query will calculate  "Total Rainfall & Mean Max Temp" by Stationn and  Year*/

SELECT 	ST_DIM.STATION_ID,
		ST_DIM.STATION_CITY,
		TIME_DIM.TIME_ID,
		AVG(WTH_FACT.MAX_TEMP) OVER(PARTITION BY  ST_DIM.STATION_ID,ST_DIM.STATION_CITY,TIME_DIM.TIME_ID) " Mean Max Temp",
		SUM(WTH_FACT.RAINFALL_MM) OVER(PARTITION BY  ST_DIM.STATION_ID,ST_DIM.STATION_CITY,TIME_DIM.TIME_ID) "Total Rainfall"
FROM WEATHER_FACT WTH_FACT
INNER JOIN STATION_DIM ST_DIM
ON STATION_DIM.STATION_ID = WTH_FACT.STATION_ID
INNER JOIN TIME_DIM 
ON TIME_DIM.TIME_ID = WTH_FACT.TIME_ID
AND TIME_DIM.YEAR = WTH_FACT.YEAR


/* The following query will calculate  "Mean Max Temp" by monthe wise for all stations*/	

SELECT 	ST_DIM.STATION_ID,
		ST_DIM.STATION_CITY,
		MONTH_NAME,
		SUM(WTH_FACT.RAINFALL_MM) OVER(Partition by  ST_DIM.STATION_ID,ST_DIM.STATION_CITY,MONTH_NAME) "Total Rainfall"
FROM WEATHER_FACT WTH_FACT
INNER JOIN STATION_DIM ST_DIM
ON STATION_DIM.STATION_ID = WTH_FACT.STATION_ID
INNER JOIN TIME_DIM 
ON TIME_DIM.TIME_ID = WTH_FACT.TIME_ID
AND TIME_DIM.YEAR = WTH_FACT.YEAR
AND TIME_DIM.MONTH_NO = WTH_FACT.MONTH

/* The following query will calculate  "Avg_RainFall" by three hours Interval time for every month*/	
SELECT TIME_BUCKET('3 HOURS', TIME,,
        START_DATE, END_DATE) AS THREE_HOUR, AVG(WTH_FACT.RAINFALL_MM) AVG_RAINFALL
FROM WEATHER_FACT WTH_FACT
INNER JOIN TIME_DIM 
ON TIME_DIM.TIME_ID = WTH_FACT.TIME_ID
AND TIME_DIM.YEAR = WTH_FACT.YEAR
AND TIME_DIM.MONTH_NO = WTH_FACT.MONTH
GROUP BY THREE_HOUR
 
	
	